"use client";
import { type DraftFor, type CostOption, newCostOption, newId } from "@/lib/drafts";
import { calculateCosts, currencies, formatMoney, numericError } from "@/lib/calculations";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Field, SelectField, AddButton, RemoveButton, SectionHeading, ResultBox } from "./fields";

export function CostBenefit({ draft, onChange }: { draft: DraftFor<"cost-benefit-analysis">; onChange: (draft: DraftFor<"cost-benefit-analysis">) => void }) {
  const result = calculateCosts(draft);
  const edit = (id: string, patch: Partial<CostOption>) => onChange({ ...draft, options: draft.options.map((option) => option.id === id ? { ...option, ...patch } : option) });
  const money = (value: number) => formatMoney(value, currencies.some((c) => c === draft.currency) ? draft.currency : "USD");
  return <section className="worksheet-section">
    <SectionHeading title="Set the same basis for every option" description="Enter each amount for the whole evaluation period. Keep nonmonetary considerations in the notes." />
    <div className="mb-7 grid max-w-xl gap-4 sm:grid-cols-2"><SelectField label="Currency" value={draft.currency} onChange={(currency) => onChange({ ...draft, currency })}>{currencies.map((currency) => <option key={currency} value={currency}>{currency}</option>)}</SelectField><Field label="Evaluation period" value={draft.period} onChange={(period) => onChange({ ...draft, period })} placeholder="e.g. 1 year" /></div>
    <SectionHeading title="Costs and benefits" action={<AddButton onClick={() => onChange({ ...draft, options: [...draft.options, newCostOption(newId())] })}>Add option</AddButton>} />
    <div className="space-y-5">{draft.options.map((option, index) => <section key={option.id} className="worksheet-panel" aria-label={`Cost–benefit option ${index + 1}`}><div className="mb-5 flex items-end gap-4"><Field label={`Option ${index + 1} name`} className="grow" value={option.name} onChange={(name) => edit(option.id, { name })} placeholder="What are you considering?" /><RemoveButton label={`Remove option ${index + 1}`} disabled={draft.options.length <= 2} onClick={() => onChange({ ...draft, options: draft.options.filter((o) => o.id !== option.id) })} /></div>
      <div className="space-y-3">{option.items.map((item, row) => { const updateItem = (patch: Partial<typeof item>) => edit(option.id, { items: option.items.map((i) => i.id === item.id ? { ...i, ...patch } : i) }); return <div key={item.id} className="grid grid-cols-[1fr_auto] items-start gap-3 rounded-md bg-secondary/65 p-3.5 sm:grid-cols-[minmax(140px,1fr)_125px_minmax(110px,160px)_32px]"><Field label={`Option ${index + 1}, item ${row + 1} description`} className="col-span-2 sm:col-span-1" value={item.description} onChange={(description) => updateItem({ description })} placeholder={item.type === "cost" ? "e.g. Subscription fee" : "e.g. Value of time saved"} /><SelectField label={`Option ${index + 1}, item ${row + 1} type`} value={item.type} onChange={(type) => updateItem({ type: type as "cost" | "benefit" })}><option value="cost">Cost</option><option value="benefit">Benefit</option></SelectField><Field label={`Amount (${draft.currency}) for option ${index + 1}, item ${row + 1}`} value={item.amount} inputMode="decimal" error={numericError(item.amount)} onChange={(amount) => updateItem({ amount })} placeholder="0.00" /><div className="sm:pt-7"><RemoveButton label={`Remove item ${row + 1} from option ${index + 1}`} onClick={() => edit(option.id, { items: option.items.filter((i) => i.id !== item.id) })} /></div></div>; })}</div>
      <div className="my-4"><AddButton onClick={() => edit(option.id, { items: [...option.items, { id: newId(), description: "", amount: "", type: "cost" }] })}>Add line item</AddButton></div>
      <Field label={`Nonmonetary considerations for option ${index + 1}`} value={option.notes} onChange={(notes) => edit(option.id, { notes })} multiline placeholder="Time, stress, relationships, flexibility, or anything an amount cannot capture." />
    </section>)}</div>
    <ResultBox title="Your comparison"><p className="mb-4 text-sm text-muted-foreground">Net benefit = total benefits − total costs, over {draft.period || "your evaluation period"}.</p><Table><TableHeader><TableRow><TableHead>Option</TableHead><TableHead className="text-right">Costs</TableHead><TableHead className="text-right">Benefits</TableHead><TableHead className="text-right">Net benefit</TableHead></TableRow></TableHeader><TableBody>{result.options.map((option, i) => <TableRow key={option.id}><TableCell className="whitespace-normal font-medium">{option.name || `Option ${i + 1}`}</TableCell><TableCell className="number text-right">{option.costs === null ? "—" : money(option.costs)}</TableCell><TableCell className="number text-right">{option.benefits === null ? "—" : money(option.benefits)}</TableCell><TableCell className="number text-right font-semibold">{option.score === null ? "Incomplete" : money(option.score)}</TableCell></TableRow>)}</TableBody></Table>
      {!result.ready ? <p className="mt-4 text-sm text-muted-foreground">Name each option and complete its line items to compare. Remove unused rows; use 0 for a known zero amount.</p> : <p className="mt-4 text-sm">{result.ranking[0].tied ? "The highest net benefit is tied. Review the nonmonetary considerations to understand the differences." : <><strong>{result.ranking[0].name}</strong> has the highest estimated net benefit. {result.ranking[0].score < 0 ? "All options have costs greater than their estimated benefits. " : ""}Check the estimates and qualitative notes before deciding.</>}</p>}
    </ResultBox>
  </section>;
}
