"use client";
import { ArrowDownRight, CalendarDays, CircleCheck, CircleSlash, UserRound } from "lucide-react";
import { type DraftFor, newId, quadrantKeys, quadrants, type Task } from "@/lib/drafts";
import { Field, SelectField, AddButton, RemoveButton, SectionHeading, ResultBox } from "./fields";

const icons = { do: CircleCheck, schedule: CalendarDays, delegate: UserRound, eliminate: CircleSlash };
export function Eisenhower({ draft, onChange }: { draft: DraftFor<"eisenhower-matrix">; onChange: (draft: DraftFor<"eisenhower-matrix">) => void }) {
  const edit = (id: string, patch: Partial<Task>) => onChange({ ...draft, tasks: draft.tasks.map((task) => task.id === id ? { ...task, ...patch } : task) });
  const count = draft.tasks.filter((task) => task.title.trim()).length;
  return <section className="worksheet-section">
    <SectionHeading title="Your priority matrix" description="Add tasks where they belong. You can move them as your priorities change." />
    <div className="mb-3 hidden grid-cols-2 gap-5 pl-9 text-center text-xs font-semibold uppercase tracking-wider text-muted-foreground md:grid"><span>Urgent</span><span>Not urgent</span></div>
    <div className="relative md:pl-9"><span className="absolute left-0 top-[15%] hidden text-xs font-semibold uppercase tracking-wider text-muted-foreground md:block [writing-mode:vertical-rl]">Important</span><span className="absolute left-0 top-[65%] hidden text-xs font-semibold uppercase tracking-wider text-muted-foreground md:block [writing-mode:vertical-rl]">Not important</span>
      <div className="grid gap-4 md:grid-cols-2">{quadrantKeys.map((key, index) => {
        const quadrant = quadrants[key]; const Icon = icons[key]; const tasks = draft.tasks.filter((task) => task.quadrant === key);
        return <section key={key} aria-label={`${quadrant.name} quadrant`} className={`flex min-h-[235px] flex-col rounded-lg border ${key === "do" ? "border-[#becce7] bg-[#f8faff]" : "bg-white"}`}>
          <div className="border-b px-5 py-4"><div className="flex items-center justify-between"><h3 className={`flex items-center gap-2 text-base font-semibold ${key === "do" ? "text-primary" : ""}`}><Icon size={17} strokeWidth={1.6} />{quadrant.name}</h3><span className="number text-xs text-muted-foreground">0{index + 1}</span></div><p className="mt-1 text-xs text-muted-foreground">{quadrant.importance} · {quadrant.urgency}</p></div>
          <div className="flex grow flex-col p-5"><p className="mb-4 text-sm text-muted-foreground">{quadrant.hint}</p><div className="space-y-4">{tasks.map((task, i) => <div key={task.id} className="rounded-md border bg-white p-3.5"><div className="mb-2 flex items-center justify-between"><span className="text-xs text-muted-foreground">Task {i + 1}</span><RemoveButton label={`Remove ${task.title || `task ${i + 1}`} from ${quadrant.name}`} onClick={() => onChange({ ...draft, tasks: draft.tasks.filter((t) => t.id !== task.id) })} /></div><Field label="Task" value={task.title} onChange={(title) => edit(task.id, { title })} placeholder="What needs to get done?" /><div className="mt-3"><Field label="Next action (optional)" value={task.action} onChange={(action) => edit(task.id, { action })} placeholder="The smallest useful step" /></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Date (optional)" type="date" value={task.date} onChange={(date) => edit(task.id, { date })} /><Field label="Owner (optional)" value={task.owner} onChange={(owner) => edit(task.id, { owner })} placeholder="Who will do this?" /></div><div className="mt-3"><SelectField label="Move to quadrant" value={task.quadrant} onChange={(quadrant) => edit(task.id, { quadrant: quadrant as Task["quadrant"] })}>{quadrantKeys.map((q) => <option key={q} value={q}>{quadrants[q].name}</option>)}</SelectField></div></div>)}</div><div className="mt-auto pt-4"><AddButton onClick={() => onChange({ ...draft, tasks: [...draft.tasks, { id: newId(), title: "", action: "", date: "", owner: "", quadrant: key }] })}>Add task to {quadrant.name.toLowerCase()}</AddButton></div></div>
        </section>;
      })}</div>
    </div>
    <ResultBox title="Your next moves">{count === 0 ? <p className="text-sm text-muted-foreground">Start with the tasks on your mind. The matrix will help you give each one a clear next action.</p> : <div className="grid gap-5 sm:grid-cols-2">{quadrantKeys.map((key) => { const tasks = draft.tasks.filter((t) => t.quadrant === key && t.title.trim()); return <div key={key}><h3 className="mb-1 text-sm font-semibold">{quadrants[key].name} <span className="ml-1 font-normal text-muted-foreground">{tasks.length} {tasks.length === 1 ? "task" : "tasks"}</span></h3>{tasks.length > 0 && <><ul className="space-y-1 text-sm">{tasks.map((task) => <li key={task.id} className="flex items-start gap-2"><ArrowDownRight size={14} className="mt-1 shrink-0 text-primary" /><span>{task.title}</span></li>)}</ul><p className="mt-2 text-xs leading-5 text-muted-foreground">{quadrants[key].prompt}</p></>}</div>; })}</div>}</ResultBox>
  </section>;
}
