"use client";
import { type DraftFor, newId } from "@/lib/drafts";
import { Field, AddButton, RemoveButton, SectionHeading, ResultBox } from "./fields";

export function PreMortem({ draft, onChange }: { draft: DraftFor<"pre-mortem-analysis">; onChange: (draft: DraftFor<"pre-mortem-analysis">) => void }) {
  const risks = draft.risks.filter((risk) => risk.cause.trim());
  const missing = risks.filter((risk) => !risk.prevention.trim());
  return <section className="worksheet-section">
    <SectionHeading title="Imagine the plan has failed" description="Start from that future outcome. What could explain it?" />
    <div className="grid gap-5 md:grid-cols-[1fr_2fr]"><Field label="When are you looking back from?" value={draft.horizon} onChange={(horizon) => onChange({ ...draft, horizon })} placeholder="e.g. Three months from now" /><Field multiline label="What does failure look like?" value={draft.failure} onChange={(failure) => onChange({ ...draft, failure })} placeholder="Describe what went wrong and what you had hoped would happen instead." /></div>
    <div className="mt-8"><SectionHeading title="Work backward from the risks" description="Turn each possible cause into an action you can take now." action={<AddButton onClick={() => onChange({ ...draft, risks: [...draft.risks, { id: newId(), cause: "", warning: "", prevention: "", owner: "" }] })}>Add risk</AddButton>} /><div className="space-y-4">{draft.risks.map((risk, index) => { const edit = (patch: Partial<typeof risk>) => onChange({ ...draft, risks: draft.risks.map((r) => r.id === risk.id ? { ...r, ...patch } : r) }); return <section key={risk.id} className="worksheet-panel" aria-label={`Risk ${index + 1}`}><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold">Possible cause {index + 1}</h3><RemoveButton label={`Remove risk ${index + 1}`} onClick={() => onChange({ ...draft, risks: draft.risks.filter((r) => r.id !== risk.id) })} /></div><div className="grid gap-4 sm:grid-cols-2"><Field multiline label={`Cause for risk ${index + 1}`} value={risk.cause} onChange={(cause) => edit({ cause })} placeholder="Why might the plan fail?" /><Field multiline label={`Early warning for risk ${index + 1}`} value={risk.warning} onChange={(warning) => edit({ warning })} placeholder="What would tell you this is starting to happen?" /><Field multiline label={`Prevention action for risk ${index + 1}`} value={risk.prevention} onChange={(prevention) => edit({ prevention })} placeholder="What can you do to reduce this risk?" /><Field label={`Owner for risk ${index + 1} (optional)`} value={risk.owner} onChange={(owner) => edit({ owner })} placeholder="Who will take this action?" /></div></section>; })}</div></div>
    <ResultBox title="Turn foresight into action">{risks.length === 0 ? <p className="text-sm text-muted-foreground">Add a possible cause of failure to start your prevention plan.</p> : <><p className="mb-4 text-sm">{risks.length} {risks.length === 1 ? "risk identified" : "risks identified"} · {risks.length - missing.length} with a prevention action</p><ul className="space-y-3">{risks.map((risk) => <li key={risk.id} className="rounded-md border bg-white p-4"><p className="text-sm font-semibold">{risk.cause}</p><p className={`mt-1 text-sm ${risk.prevention.trim() ? "" : "text-muted-foreground"}`}>{risk.prevention.trim() ? risk.prevention : "Next step: add a prevention action for this risk."}</p>{risk.warning.trim() && <p className="mt-2 text-xs text-muted-foreground">Watch for: {risk.warning}</p>}{risk.owner.trim() && <p className="mt-1 text-xs text-muted-foreground">Owner: {risk.owner}</p>}</li>)}</ul>{missing.length > 0 && <p className="mt-4 text-sm text-muted-foreground">{missing.length} {missing.length === 1 ? "risk still needs" : "risks still need"} a prevention action.</p>}</>}</ResultBox>
  </section>;
}
