"use client";
import { type DraftFor, newId } from "@/lib/drafts";
import { calculateRice, formatNumber, numericError } from "@/lib/calculations";
import { Field, SelectField, AddButton, RemoveButton, SectionHeading, ResultBox } from "./fields";

export function Rice({ draft, onChange }: { draft: DraftFor<"rice-scoring">; onChange: (draft: DraftFor<"rice-scoring">) => void }) {
  const result = calculateRice(draft);
  return <section className="worksheet-section">
    <SectionHeading title="Ideas" description="Estimate reach for the same period." action={<AddButton onClick={() => onChange({ ...draft, options: [...draft.options, { id: newId(), name: "", reach: "", impact: "", confidence: "", effort: "", notes: "" }] })}>Add idea</AddButton>} />
    <Field className="mb-6 max-w-sm" label="Reach period" value={draft.period} onChange={(period) => onChange({ ...draft, period })} placeholder="e.g. Next quarter" />
    <div className="space-y-10">{draft.options.map((option, index) => {
      const edit = (patch: Partial<typeof option>) => onChange({ ...draft, options: draft.options.map((o) => o.id === option.id ? { ...o, ...patch } : o) });
      return <section key={option.id} className="worksheet-panel" aria-label={`RICE idea ${index + 1}`}><div className="mb-5 flex items-end gap-4"><Field className="grow worksheet-title" label={`Idea ${index + 1} name`} displayLabel={`Idea ${index + 1}`} value={option.name} onChange={(name) => edit({ name })} placeholder="What could you work on?" /><RemoveButton label={`Remove idea ${index + 1}`} disabled={draft.options.length <= 2} onClick={() => onChange({ ...draft, options: draft.options.filter((o) => o.id !== option.id) })} /></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label={`Reach for idea ${index + 1}`} displayLabel="Reach" value={option.reach} inputMode="decimal" error={numericError(option.reach)} onChange={(reach) => edit({ reach })} placeholder="e.g. 1000" hint="People or events." /><SelectField label={`Impact for idea ${index + 1}`} displayLabel="Impact" value={option.impact} onChange={(impact) => edit({ impact })}><option value="">Select impact</option><option value="0.25">0.25 — Minimal</option><option value="0.5">0.5 — Low</option><option value="1">1 — Medium</option><option value="2">2 — High</option><option value="3">3 — Massive</option></SelectField><SelectField label={`Confidence for idea ${index + 1}`} displayLabel="Confidence" value={option.confidence} onChange={(confidence) => edit({ confidence })}><option value="">Select confidence</option><option value="50">50% — Low</option><option value="80">80% — Medium</option><option value="100">100% — High</option></SelectField><Field label={`Effort for idea ${index + 1}`} displayLabel="Effort" value={option.effort} inputMode="decimal" error={numericError(option.effort, { positive: true })} onChange={(effort) => edit({ effort })} placeholder="e.g. 2" hint="Person-months." /></div><details className="mt-4 text-sm"><summary className="cursor-pointer text-muted-foreground">Notes (optional)</summary><Field className="mt-3" multiline displayLabel="Evidence and dependencies" label={`Evidence and dependencies for idea ${index + 1}`} value={option.notes} onChange={(notes) => edit({ notes })} placeholder="Sources or prerequisites" /></details></section>;
    })}</div>
    <ResultBox title="Your priorities"><p className="mb-4 text-sm text-muted-foreground">Score = reach × impact × (confidence / 100) ÷ effort.</p>{result.ranking.length === 0 ? <p className="text-sm">Complete an idea to see its score.</p> : <><p className="mb-3 text-xs font-medium text-muted-foreground">{result.ready ? "Complete comparison" : "Provisional ranking — some ideas are incomplete"}</p><ol className="space-y-2">{result.ranking.map((option) => <li key={option.id} className="flex justify-between gap-4 py-3"><span><span className="mr-3 text-muted-foreground">{option.rank}.</span>{option.name}{option.tied && <span className="ml-2 text-xs text-muted-foreground">Tied</span>}</span><strong className="number text-primary">{formatNumber(option.score)}</strong></li>)}</ol></>}{result.options.some((option) => option.score === null && option.name.trim()) && <p className="mt-3 text-sm text-muted-foreground">Still to complete: {result.options.filter((option) => option.score === null && option.name.trim()).map((option) => option.name).join(", ")}.</p>}</ResultBox>
  </section>;
}
