"use client";
import { type DraftFor, newId } from "@/lib/drafts";
import { calculateRice, formatNumber, numericError } from "@/lib/calculations";
import { Field, SelectField, AddButton, RemoveButton, SectionHeading, ResultBox } from "./fields";

export function Rice({ draft, onChange }: { draft: DraftFor<"rice-scoring">; onChange: (draft: DraftFor<"rice-scoring">) => void }) {
  const result = calculateRice(draft);
  return <section className="worksheet-section">
    <SectionHeading title="Score your ideas" description="Use the same reach period and effort unit for every idea." action={<AddButton onClick={() => onChange({ ...draft, options: [...draft.options, { id: newId(), name: "", reach: "", impact: "", confidence: "", effort: "", notes: "" }] })}>Add idea</AddButton>} />
    <Field className="mb-6 max-w-sm" label="Reach period" value={draft.period} onChange={(period) => onChange({ ...draft, period })} placeholder="e.g. Next quarter" />
    <div className="space-y-4">{draft.options.map((option, index) => {
      const edit = (patch: Partial<typeof option>) => onChange({ ...draft, options: draft.options.map((o) => o.id === option.id ? { ...o, ...patch } : o) });
      return <section key={option.id} className="worksheet-panel" aria-label={`RICE idea ${index + 1}`}><div className="mb-5 flex items-end gap-4"><Field className="grow" label={`Idea ${index + 1} name`} value={option.name} onChange={(name) => edit({ name })} placeholder="What could you work on?" /><RemoveButton label={`Remove idea ${index + 1}`} disabled={draft.options.length <= 2} onClick={() => onChange({ ...draft, options: draft.options.filter((o) => o.id !== option.id) })} /></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label={`Reach for idea ${index + 1}`} value={option.reach} inputMode="decimal" error={numericError(option.reach)} onChange={(reach) => edit({ reach })} placeholder="e.g. 1000" hint="People or events in the shared period." /><SelectField label={`Impact for idea ${index + 1}`} value={option.impact} onChange={(impact) => edit({ impact })} hint="Impact on one person or event."><option value="">Select impact</option><option value="0.25">0.25 — Minimal</option><option value="0.5">0.5 — Low</option><option value="1">1 — Medium</option><option value="2">2 — High</option><option value="3">3 — Massive</option></SelectField><SelectField label={`Confidence for idea ${index + 1}`} value={option.confidence} onChange={(confidence) => edit({ confidence })} hint="How strong is your evidence?"><option value="">Select confidence</option><option value="50">50% — Low</option><option value="80">80% — Medium</option><option value="100">100% — High</option></SelectField><Field label={`Effort for idea ${index + 1}`} value={option.effort} inputMode="decimal" error={numericError(option.effort, { positive: true })} onChange={(effort) => edit({ effort })} placeholder="e.g. 2" hint="Person-months. Two people × one month = 2." /></div><div className="mt-5"><Field multiline label={`Evidence and dependencies for idea ${index + 1}`} value={option.notes} onChange={(notes) => edit({ notes })} placeholder="Where did these estimates come from? Does anything need to happen first?" /></div></section>;
    })}</div>
    <ResultBox title="Your priorities"><p className="mb-4 text-sm text-muted-foreground">RICE score = reach × impact × confidence ÷ effort. Confidence is converted from a percentage.</p>{result.ranking.length === 0 ? <p className="text-sm">Name an idea and fill in all four factors to see its score.</p> : <><p className="mb-3 text-xs font-medium text-muted-foreground">{result.ready ? "Complete comparison" : "Provisional ranking — some ideas are incomplete"}</p><ol className="space-y-2">{result.ranking.map((option) => <li key={option.id} className="flex justify-between gap-4 rounded-md border bg-white p-4"><span><span className="mr-3 text-muted-foreground">{option.rank}.</span>{option.name}{option.tied && <span className="ml-2 text-xs text-muted-foreground">Tied</span>}</span><strong className="number text-primary">{formatNumber(option.score)}</strong></li>)}</ol><p className="mt-4 text-sm text-muted-foreground">Check the evidence and dependencies before committing to the order.</p></>}{result.options.some((option) => option.score === null && option.name.trim()) && <p className="mt-3 text-sm text-muted-foreground">Still to complete: {result.options.filter((option) => option.score === null && option.name.trim()).map((option) => option.name).join(", ")}.</p>}</ResultBox>
  </section>;
}
