"use client";
import { type DraftFor, newId } from "@/lib/drafts";
import { Field, AddButton, RemoveButton, SectionHeading, ResultBox } from "./fields";

export function TenTenTen({ draft, onChange }: { draft: DraftFor<"ten-ten-ten">; onChange: (draft: DraftFor<"ten-ten-ten">) => void }) {
  const horizons = [{ key: "minutes", name: "10 minutes", hint: "The immediate feelings and consequences." }, { key: "months", name: "10 months", hint: "How might everyday life have changed?" }, { key: "years", name: "10 years", hint: "What might this mean for the life you want?" }] as const;
  return <section className="worksheet-section">
    <SectionHeading title="Look at each choice over time" description="Write what you anticipate, including both the consequences and how you might feel." action={<AddButton onClick={() => onChange({ ...draft, options: [...draft.options, { id: newId(), name: "", minutes: "", months: "", years: "" }] })}>Add option</AddButton>} />
    <div className="space-y-5">{draft.options.map((option, index) => <section key={option.id} className="worksheet-panel" aria-label={`Reflection option ${index + 1}`}><div className="mb-5 flex items-end gap-4"><Field className="grow" label={`Option ${index + 1} name`} value={option.name} onChange={(name) => onChange({ ...draft, options: draft.options.map((o) => o.id === option.id ? { ...o, name } : o) })} placeholder="What could you choose?" /><RemoveButton label={`Remove option ${index + 1}`} disabled={draft.options.length <= 2} onClick={() => onChange({ ...draft, options: draft.options.filter((o) => o.id !== option.id) })} /></div><div className="grid gap-5 md:grid-cols-3">{horizons.map((horizon, i) => <div key={horizon.key} className="min-w-0"><p className="eyebrow mb-3">0{i + 1} · {i === 0 ? "Right after" : i === 1 ? "A little later" : "The longer view"}</p><Field multiline label={`Option ${index + 1}: ${horizon.name}`} value={option[horizon.key]} onChange={(value) => onChange({ ...draft, options: draft.options.map((o) => o.id === option.id ? { ...o, [horizon.key]: value } : o) })} placeholder={horizon.hint} /></div>)}</div></section>)}</div>
    <div className="mt-6"><Field multiline label="Which values and priorities matter here?" value={draft.values} onChange={(values) => onChange({ ...draft, values })} placeholder="Consider things such as family, learning, stability, autonomy, or your current commitments." /></div>
    <ResultBox title="Step back and reflect"><ul className="list-disc space-y-2 pl-5 text-sm leading-6"><li>Which option fits the priorities you wrote down?</li><li>Are short-term discomfort or relief overshadowing longer-term consequences?</li><li>What information would make you more comfortable with your choice?</li></ul><p className="mt-4 text-sm text-muted-foreground">There is no calculated winner. Use your reflections to write your decision and next step below.</p></ResultBox>
  </section>;
}
