"use client";
import { type CSSProperties } from "react";
import { type DraftFor, newId } from "@/lib/drafts";
import { calculateWeighted, formatNumber } from "@/lib/calculations";
import { Field, SelectField, AddButton, RemoveButton, SectionHeading, ResultBox } from "./fields";

export function Weighted({ draft, onChange }: { draft: DraftFor<"weighted-scoring">; onChange: (draft: DraftFor<"weighted-scoring">) => void }) {
  const result = calculateWeighted(draft);
  const addOption = () => onChange({ ...draft, options: [...draft.options, { id: newId(), name: "", ratings: {} }] });
  return <section className="worksheet-section">
    <SectionHeading title="1. What matters to you?" description="Name each criterion and give it an importance weight. 1 = less important; 5 = very important." action={<AddButton onClick={() => onChange({ ...draft, criteria: [...draft.criteria, { id: newId(), name: "", weight: "3" }] })}>Add criterion</AddButton>} />
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{draft.criteria.map((criterion, i) => <div key={criterion.id} className="rounded-lg border bg-secondary/40 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs text-muted-foreground">Criterion {i + 1}</span><RemoveButton label={`Remove criterion ${i + 1}`} disabled={draft.criteria.length <= 1} onClick={() => onChange({ ...draft, criteria: draft.criteria.filter((c) => c.id !== criterion.id), options: draft.options.map((o) => ({ ...o, ratings: Object.fromEntries(Object.entries(o.ratings).filter(([key]) => key !== criterion.id)) })) })} /></div><Field label={`Criterion ${i + 1} name`} value={criterion.name} placeholder={i === 0 ? "e.g. Affordability" : i === 1 ? "e.g. Ease of use" : "e.g. Flexibility"} onChange={(name) => onChange({ ...draft, criteria: draft.criteria.map((c) => c.id === criterion.id ? { ...c, name } : c) })} /><div className="mt-3"><SelectField label={`Criterion ${i + 1} weight`} value={criterion.weight} onChange={(weight) => onChange({ ...draft, criteria: draft.criteria.map((c) => c.id === criterion.id ? { ...c, weight } : c) })}>{[1, 2, 3, 4, 5].map((n) => <option key={n} value={n}>{n}{n === 1 ? " — Less important" : n === 5 ? " — Very important" : ""}</option>)}</SelectField></div></div>)}</div>
    <div className="mt-8"><SectionHeading title="2. Rate your options" description="Rate desirability from 1 to 5. For affordability, a lower cost should receive a higher rating." action={<AddButton onClick={addOption}>Add option</AddButton>} />
      <div className="overflow-x-auto rounded-lg border"><div className="scoring-grid" style={{ "--criteria-count": draft.criteria.length } as CSSProperties}>
        <div className="scoring-row scoring-head hidden bg-secondary text-xs text-muted-foreground md:grid"><span>Option</span>{draft.criteria.map((criterion, i) => <span key={criterion.id}>{criterion.name || `Criterion ${i + 1}`} <span className="font-normal">· weight {criterion.weight}</span></span>)}<span /></div>
        {draft.options.map((option, i) => <div key={option.id} className="scoring-row grid gap-4 border-t p-4 first:border-t-0 md:items-end"><Field label={`Option ${i + 1} name`} value={option.name} placeholder={`Name option ${i + 1}`} onChange={(name) => onChange({ ...draft, options: draft.options.map((o) => o.id === option.id ? { ...o, name } : o) })} />{draft.criteria.map((criterion, ci) => <SelectField key={criterion.id} label={`${option.name || `Option ${i + 1}`}: ${criterion.name || `Criterion ${ci + 1}`}`} value={option.ratings[criterion.id] ?? ""} onChange={(rating) => onChange({ ...draft, options: draft.options.map((o) => o.id === option.id ? { ...o, ratings: { ...o.ratings, [criterion.id]: rating } } : o) })}><option value="">Select rating</option>{[1, 2, 3, 4, 5].map((n) => <option key={n} value={n}>{n}{n === 1 ? " — Least desirable" : n === 5 ? " — Most desirable" : ""}</option>)}</SelectField>)}<div className="pb-1"><RemoveButton label={`Remove option ${i + 1}`} disabled={draft.options.length <= 2} onClick={() => onChange({ ...draft, options: draft.options.filter((o) => o.id !== option.id) })} /></div></div>)}
      </div></div>
    </div>
    <ResultBox title="Your comparison"><p className="mb-4 text-sm text-muted-foreground">Weighted score = sum of (weight × rating) ÷ total weight. Scores range from 1 to 5.</p>{!result.ready ? <p className="text-sm">Name every criterion and option, then fill in all ratings to see a complete comparison.</p> : <><ol className="space-y-3">{result.ranking.map((option) => <li key={option.id} className="rounded-md border bg-white p-4"><div className="flex justify-between gap-4"><span className="font-medium"><span className="mr-3 text-sm text-muted-foreground">{option.rank}.</span>{option.name}{option.tied && <span className="ml-2 text-xs text-muted-foreground">Tied</span>}</span><strong className="number text-primary">{formatNumber(option.score)} <span className="text-xs font-normal text-muted-foreground">/ 5</span></strong></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{result.options.find((o) => o.id === option.id)?.contributions.map((c) => `${c.name}: ${formatNumber(c.contribution)} points`).join(" · ")}</p></li>)}</ol><p className="mt-4 text-sm text-muted-foreground">Review the trade-offs. Would your choice change if you adjusted the most important weight?</p></>}</ResultBox>
  </section>;
}
