import { describe, it, expect } from "vitest";
import { createDraftStore, storageKey, savedDraftIds } from "../../lib/draft-store";
import { createDraft } from "../../lib/drafts";

function memoryStorage() {
  const data = new Map<string, string>();
  return { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => { data.set(key, value); }, removeItem: (key: string) => { data.delete(key); } };
}
describe("browser draft persistence", () => {
  it("restores existing work before enabling edits and never writes on hydration", () => { const storage = memoryStorage(); const draft = { ...createDraft("eisenhower-matrix"), title: "Keep this decision" }; const raw = JSON.stringify(draft); storage.setItem(storageKey(draft.frameworkId), raw); const store = createDraftStore(draft.frameworkId, () => storage); expect(store.getSnapshot().status).toBe("loading"); store.subscribe(() => {}); expect(store.getSnapshot().draft.title).toBe("Keep this decision"); expect(storage.getItem(storageKey(draft.frameworkId))).toBe(raw); });
  it("writes every edit immediately and restores it in a new store", () => { const storage = memoryStorage(); const store = createDraftStore("rice-scoring", () => storage); store.subscribe(() => {}); store.update({ ...store.getSnapshot().draft, title: "Q4 roadmap" }); expect(store.getSnapshot().status).toBe("saved"); const reopened = createDraftStore("rice-scoring", () => storage); reopened.subscribe(() => {}); expect(reopened.getSnapshot().draft.title).toBe("Q4 roadmap"); expect(savedDraftIds(storage, ["rice-scoring", "weighted-scoring"])).toEqual(["rice-scoring"]); });
  it("keeps corrupt data untouched while allowing unsaved editing", () => { const storage = memoryStorage(); const key = storageKey("rice-scoring"); storage.setItem(key, "broken data"); const store = createDraftStore("rice-scoring", () => storage); store.subscribe(() => {}); expect(store.getSnapshot().status).toBe("corrupt"); store.update({ ...store.getSnapshot().draft, title: "New thought" }); expect(store.getSnapshot().draft.title).toBe("New thought"); expect(storage.getItem(key)).toBe("broken data"); store.reset(); expect(storage.getItem(key)).toBeNull(); expect(store.getSnapshot().status).toBe("ready"); });
  it("keeps unsaved work after quota failures and retries successfully", () => { const storage = memoryStorage(); let unavailable = true; const port = { ...storage, setItem: (key: string, value: string) => { if (unavailable) throw new Error("quota"); storage.setItem(key, value); } }; const store = createDraftStore("ten-ten-ten", () => port); store.subscribe(() => {}); store.update({ ...store.getSnapshot().draft, title: "Keep in memory" }); expect(store.getSnapshot().status).toBe("unavailable"); unavailable = false; store.update({ ...store.getSnapshot().draft, context: "Try again" }); expect(store.getSnapshot().status).toBe("saved"); expect(storage.getItem(storageKey("ten-ten-ten"))).toContain("Keep in memory"); });
  it("does not crash when storage access is blocked", () => { const store = createDraftStore("pre-mortem-analysis", () => { throw new Error("denied"); }); store.subscribe(() => {}); expect(store.getSnapshot().status).toBe("unavailable"); store.update({ ...store.getSnapshot().draft, title: "Still editable" }); expect(store.getSnapshot().draft.title).toBe("Still editable"); store.reset(); expect(store.getSnapshot().draft.title).toBe("Still editable"); });
  it("does not overwrite changes from another tab", () => { const storage = memoryStorage(); const a = createDraftStore("rice-scoring", () => storage); const b = createDraftStore("rice-scoring", () => storage); a.subscribe(() => {}); b.subscribe(() => {}); a.update({ ...a.getSnapshot().draft, title: "Tab A" }); b.update({ ...b.getSnapshot().draft, title: "Tab B" }); expect(b.getSnapshot().status).toBe("conflict"); expect(b.getSnapshot().draft.title).toBe("Tab B"); expect(storage.getItem(storageKey("rice-scoring"))).toContain("Tab A"); });
  it("reset removes only the current framework and rejects wrong-framework updates", () => { const storage = memoryStorage(); const a = createDraftStore("rice-scoring", () => storage); const b = createDraftStore("weighted-scoring", () => storage); a.subscribe(() => {}); b.subscribe(() => {}); a.update({ ...a.getSnapshot().draft, title: "Rice" }); b.update({ ...b.getSnapshot().draft, title: "Weighted" }); a.reset(); expect(storage.getItem(storageKey("rice-scoring"))).toBeNull(); expect(storage.getItem(storageKey("weighted-scoring"))).toContain("Weighted"); expect(() => a.update(b.getSnapshot().draft)).toThrow(); });
});
